on: 
  [push]
  schedule:
    - cron: '0 * * * *'

jobs:
  update_notebook:
    runs-on: ubuntu-latest
    name: update notebook
    steps:
    - name: Get the output time
      uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x' 
    - name: Install Python dependencies
      run: pip3 install -r requirements.txt
    - name: update data
      run: python3 genderstat.py
    - name: run notebook
      run: |
        pip install papermill ipykernel jupyter pandas numpy matplotlib
        python3 -m ipykernel install --user --name python3
        #sudo chmod -R 777 .
        papermill --kernel python3 graph.ipynb graph.ipynb
    - name: Commit files
      run: |
        git config --local user.email "tomsurayo@gmail.com"
        git config --local user.name "ninabcdefghi"
        git commit -m "Add changes" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}